# Generated by Django 4.1.3 on 2022-11-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_password_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.TextField(unique=True),
        ),
    ]
