# Generated by Django 4.1.3 on 2022-11-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_remove_board_threads'),
        ('threads', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='posts',
        ),
        migrations.AddField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boards.board'),
        ),
    ]
